/*
Auto-generated by gltfjsx, then adjusted for project usage.
Source: public/assets/models/f1_car.glb
*/

import { useGLTF } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";
import { useMemo } from "react";
import { Box3, Vector3, type Mesh } from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: Mesh;
  };
};

type Props = ThreeElements["group"] & {
  targetLength?: number;
  groundOffset?: number;
};

export default function F1CarModel({
  targetLength = 2.4,
  groundOffset = 0.02,
  ...props
}: Props) {
  const { nodes } = useGLTF("/assets/models/f1_car.glb") as unknown as GLTFResult;

  const normalized = useMemo(() => {
    const geometry = nodes.mesh_0.geometry;
    geometry.computeBoundingBox();

    const bounds = geometry.boundingBox?.clone() ?? new Box3();
    const size = new Vector3();
    const center = new Vector3();

    bounds.getSize(size);
    bounds.getCenter(center);

    const safeLength = Math.max(size.z, 0.0001);
    const scaleFactor = targetLength / safeLength;
    const localGroundOffset = groundOffset / scaleFactor;

    return {
      scaleFactor,
      meshPosition: [
        -center.x,
        -bounds.min.y + localGroundOffset,
        -center.z,
      ] as [number, number, number],
    };
  }, [nodes.mesh_0.geometry, targetLength, groundOffset]);

  return (
    <group {...props} dispose={null} scale={normalized.scaleFactor}>
      <mesh
        name="mesh_0"
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
        position={normalized.meshPosition}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/assets/models/f1_car.glb");
